# Generated by Django 5.0.4 on 2024-04-25 13:05

import django.db.models.deletion
import filebrowser.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='company name')),
                ('logo', filebrowser.fields.FileBrowseField(max_length=255, verbose_name='company logo')),
                ('phone', models.CharField(max_length=255, verbose_name='company phone')),
                ('email', models.EmailField(max_length=255, verbose_name='company email')),
                ('about', tinymce.models.HTMLField(verbose_name='about company')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='activity title')),
                ('description', tinymce.models.HTMLField(verbose_name='activity description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='company.company')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
            },
        ),
    ]
